//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Opten.Common")]
[assembly: AssemblyDescription("Opten.Common")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Common")]
[assembly: AssemblyVersion("1.1.6.2")]
[assembly: AssemblyFileVersion("1.1.6.2")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2016 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("cf7a4b9f-f142-4062-8cd2-312d80d7eee4")]
[assembly: ComVisible(false)]

[assembly: InternalsVisibleTo("Opten.Common.Test")]
[assembly: InternalsVisibleTo("Opten.Umbraco.Localization.Test")]

